#huggingface上の基盤モデル名
huggingface_input_model: kanhatakeyama/0313gpt_wiki
#huggingface_input_model: kanhatakeyama/0314gpt_mc4_wiki_en   

#ファインチューニングするデータ
dataset_path: sample_data/databricks-dolly-15k-ja_converted.jsonl

#モデルの保存場所
output_tokenizer_and_model_dir: ../../models/hf_ft/0313gpt_wiki_ft
#output_tokenizer_and_model_dir: ../../models/hf_ft/0314gpt_mc4_wiki_en_ft  

#ファインチューニングモデルのアップロード名 (for huggingface)
huggingface_name: 0313gpt_wiki_ft
#huggingface_name: 0314gpt_mc4_wiki_en_ft

#test prompt
test_prompt_text: 日本の大統領の名前は?