output_path: ../../data/wikipedia_grad_en_to_ja.jsonl # output path
max_records: 1000000 #1 datasetあたりの最大件数｡debug時は小さくする
#max_records: 10000 #1 datasetあたりの最大件数｡debug時は小さくする
overwrite: True # output_pathを上書きする